name: Run Python Command
on:
  schedule:
    - cron: '30 10,22 * * *' # This cron expression runs the workflow every day at 8:00 AM and 8:00 PM GMT+8

jobs:
  run-python-command:
    runs-on: [self-hosted, macOS, ARM64, crypto]
    steps:
      - name: Install packages
        run: ls -al