name: Run Python Command
on:
  schedule:
    - cron: '0 4 * * *' # This cron expression runs the workflow every day at 8:00 AM and 8:00 PM GMT+8
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  run-python-command:
    runs-on: [self-hosted, macOS, ARM64, crypto]
    steps:
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.9"  # Replace with the desired Python version

      - uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: ./screen.db
          key: stock_db-cache

      - name: Checkout code
        uses: actions/checkout@v2

      - name: decode api
        run: echo -n ${{ secrets.API }} | base64 --decode > api_keys.json

      - name: Install packages
        run: pip3 install -r requirements.txt

      - name: Run Python command
        run: python3 stock_trend_template.py -u ${{ secrets.STOCK_WEBHOOK }}  # Replace with your Python command

      - name: Cache db
        id: cache-db
        uses: actions/cache@v3
        with:
          path: ./screen.db
          key: stock_db-cache
